const fs = require("fs");
const https = require("https");
const ts = require("typescript");

const filePath = "src/config/schema.base.generated.ts";
const source = fs.readFileSync(filePath, "utf8");
const sf = ts.createSourceFile(
  filePath,
  source,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
);

const nodes = [];

// 옵션 A 적용: key가 string literal이고 value가 string literal일 때만 번역
function visit(node) {
  if (ts.isPropertyAssignment(node)) {
    const name = node.name;
    const init = node.initializer;

    // key가 string literal인지 확인
    const isStringKey =
      ts.isStringLiteral(name) || ts.isNoSubstitutionTemplateLiteral(name);

    // value가 string literal인지 확인
    const isStringValue =
      ts.isStringLiteralLike(init) || ts.isNoSubstitutionTemplateLiteral(init);

    if (isStringKey && isStringValue) {
      nodes.push({
        start: init.getStart(sf),
        end: init.getEnd(),
        text: init.text,
      });
    }
  }

  ts.forEachChild(node, visit);
}

visit(sf);

const uniqueTexts = [...new Set(nodes.map((n) => n.text))];
console.log(
  `found ${nodes.length} string literals, ${uniqueTexts.length} unique`,
);

function translateText(text) {
  const url = new URL("https://translate.googleapis.com/translate_a/single");
  url.searchParams.set("client", "gtx");
  url.searchParams.set("sl", "en");
  url.searchParams.set("tl", "ko");
  url.searchParams.set("dt", "t");
  url.searchParams.set("q", text);

  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        let body = "";
        res.setEncoding("utf8");
        res.on("data", (chunk) => {
          body += chunk;
        });
        res.on("end", () => {
          try {
            const data = JSON.parse(body);
            const translated = data?.[0]?.[0]?.[0];
            if (typeof translated !== "string") {
              reject(
                new Error(
                  `unexpected translation payload for: ${text.slice(0, 80)}`,
                ),
              );
              return;
            }
            resolve(translated);
          } catch (error) {
            reject(
              new Error(
                `failed to parse translation response for: ${text.slice(0, 80)} :: ${String(error)}`,
              ),
            );
          }
        });
      })
      .on("error", reject);
  });
}

async function mapWithConcurrency(items, limit, fn) {
  const results = new Array(items.length);
  let index = 0;
  async function worker() {
    while (true) {
      const current = index;
      index += 1;
      if (current >= items.length) return;
      results[current] = await fn(items[current], current);
      if ((current + 1) % 50 === 0) {
        console.log(`translated ${current + 1}/${items.length}`);
      }
    }
  }
  const workers = Array.from({ length: Math.min(limit, items.length) }, worker);
  await Promise.all(workers);
  return results;
}

(async () => {
  const cache = new Map();
  const translations = await mapWithConcurrency(
    uniqueTexts,
    4,
    async (text) => {
      if (cache.has(text)) return cache.get(text);
      const translated = await translateText(text);
      cache.set(text, translated);
      return translated;
    },
  );

  const translationMap = new Map();
  uniqueTexts.forEach((text, index) =>
    translationMap.set(text, translations[index]),
  );

  const replacements = [];
  for (const node of nodes) {
    const translated = translationMap.get(node.text);
    replacements.push({
      start: node.start,
      end: node.end,
      replacement: JSON.stringify(translated),
    });
  }
  replacements.sort((a, b) => b.start - a.start);

  let nextSource = source;
  for (const { start, end, replacement } of replacements) {
    nextSource =
      nextSource.slice(0, start) + replacement + nextSource.slice(end);
  }
  nextSource = nextSource.replace(
    "// Auto-generated by scripts/generate-base-config-schema.ts. Do not edit directly.",
    "// scripts/generate-base-config-schema.ts로 자동 생성됨. 직접 수정하지 마세요.",
  );

  const tmpPath = `${filePath}.tmp`;
  fs.writeFileSync(tmpPath, nextSource, "utf8");
  fs.renameSync(tmpPath, filePath);
  console.log("wrote translated file");
})().catch((error) => {
  console.error(error);
  process.exit(1);
});
